#!/usr/bin/env sh
#
# Export variables required by bin/fresh.

# ===== Global =====
VAR_USERNAME=hawker
VAR_PROFILE=$(git rev-parse --abbrev-ref HEAD)
VAR_COMPUTER_NAME=
VAR_SOUND_EFFECT_ON_BOOT=true
VAR_SHOW_SCROLL_BARS=Always  # `WhenScrolling`, `Automatic` and `Always`
VAR_EXPAND_PRINT_PANEL_BY_DEFAULT=true
VAR_EXPAND_SAVE_PANEL_BY_DEFAULT=true
VAR_SAVE_NEW_DOCUMENTS_TO_ICLOUD=false

# ===== Security =====
VAR_CREATE_SSH_KEY=true

# ===== Dotfiles =====
# WARN: Modifying this is going to break the dotfiles script
# unless it supports the same Makefile interface of 'intstall' and 'reinstall'.
VAR_GITHUB_DOTFILES_REPO=ahawker/dotfiles

# ===== Dotfiles =====
VAR_SLEEP_AFTER_MINUTES_ON_AC=15
VAR_SLEEP_AFTER_MINUTES_ON_BATTERY=5

# ===== Finder =====
VAR_WARN_BEFORE_EMPTYING_TRASH=true

# ===== Screenshots =====
VAR_SCREENSHOT_DIR="$HOME/screenshots"
VAR_SCREENSHOT_FORMAT=png

# ===== Localization =====
VAR_LANGUAGE=en
VAR_LOCALE=en_US
VAR_CURRENCY=USD
VAR_TIME_ZONE=America/Los_Angeles
VAR_MEASUREMENT_UNITS=Centimeters
VAR_USE_METRIC=true
