#!/usr/bin/env sh
#
# Export functions for interacting with dotfiles.

DOTFILES_DIR="$HOME/dotfiles"
DOTFILES_HTTPS_URL="https://github.com/${VAR_GITHUB_DOTFILES_REPO}"
DOTFILES_GIT_URL="git@github.com/${VAR_GITHUB_DOTFILES_REPO}.git"

install_dotfiles_deps() {
    brew install --quiet stow
}

install_dotfiles() {
    BRANCH="${1:-master}"

    if [ ! -d "$DOTFILES_DIR" ]; then
        git clone "$DOTFILES_HTTPS_URL" "$DOTFILES_DIR"
        (
            cd "$DOTFILES_DIR" && \
            git checkout $BRANCH && \
            IGNORE_SHELL_RC_FILES=1 make install && \
            git remote set-url origin "$DOTFILES_GIT_URL"
        )
    else
        (
            cd "$DOTFILES_DIR" && \
            git pull --rebase --autostash && \
            git checkout $BRANCH && \
            IGNORE_SHELL_RC_FILES=1 make reinstall
        )
    fi
}
