#!/usr/bin/env sh
#
# Export functions for simple logging.

# Simple info logging.
#
# $1 - Message to write to stdout.
log() {
    echo "$*"
}

# Log a "section header" message.
#
# $1 - Message to write to stdout.
log_section() {
    echo "====== $* ======"
}

# Context manager that logs before/after the given args. It is assumed that a function
# with optional arguments is passed.
#
# Ex: log_call my_foo 42
#
# $@ - Function with arguments to call.
log_call() {
    printf -- "--> %s ... " "$*"
    "$@"
    echo "OK"
}
