#!/usr/bin/env sh
#
# Export functions for interacting with screenshots.

DEFAULT_SCREENSHOT_DIR="$HOME/screenshots"
DEFAULT_SCREENSHOT_TYPE="png"

set_screenshot_dir() {
    SCREENSHOT_DIR="${1:-DEFAULT_SCREENSHOT_DIR}"
    mkdir -p "$SCREENSHOT_DIR"
    defaults write com.apple.screencapture location -string "$SCREENSHOT_DIR"
}

set_screenshot_format() {
    defaults write com.apple.screencapture type -string "${1:-DEFAULT_SCREENSHOT_TYPE}"
}

disable_screenshot_shadows() {
    defaults write com.apple.screencapture disable-shadow -bool true
}
