#!/usr/bin/env sh
#
# Export functions for managing security settings.


# Disable Java for webkit (safari).
disable_java_for_safari_webkit() {
    defaults write com.apple.Safari \
        com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled \
        -bool false
    defaults write com.apple.Safari \
        com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles \
        -bool false
}

# Require password after 'n' seconds of screensaver.
#
# $1 - 'N' seconds before password is required; default: 3
enable_screensaver_password_prompt() {
    defaults write com.apple.screensaver askForPassword -int 1
    defaults write com.apple.screensaver askForPasswordDelay -int "${1:-3}"
}

# Enable the Application Layer Firewall (ALF).
enable_application_layer_firewall() {
    sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1
    sudo launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist 2> /dev/null
}

# Enable the file vault full disk encryption.
enable_full_disk_encryption() {
    if fdesetup status | grep -vE "FileVault is (On|Off, but will be enabled after the next restart)."; then
        sudo fdesetup enable -user $USER | tee ~/Documents/filevault-recovery-key.txt
    fi
}
