#!/usr/bin/env sh
#
# Export functions for managing Visual Studio Code (vscode).

VSCODE_DOTFILES_PATH="$HOME/vscode"
VSCODE_EXTENSIONS_PATH="$VSCODE_DOTFILES_PATH/extensions.txt"
VSCODE_SETTINGS_PATH="$VSCODE_DOTFILES_PATH/settings.json"
VSCODE_KEYBINDINGS_PATH="$VSCODE_DOTFILES_PATH/keybindings.json"

VSCODE_USER_PATH="$HOME/Library/Application Support/Code/User"
VSCODE_SETTINGS_SYMLINK_PATH="$VSCODE_USER_PATH/settings.json"
VSCODE_KEYBINDINGS_SYMLINK_PATH="$VSCODE_USER_PATH/keybindings.json"

install_vscode_extensions() {
    if [ -f "$VSCODE_EXTENSIONS_PATH" ]; then
        cat "$VSCODE_EXTENSIONS_PATH" | xargs -n1 code --install-extension
    fi
}

install_vscode_config() {
    if ! [ -f "$VSCODE_SETTINGS_SYMLINK_PATH" ]; then
        ln -s "$VSCODE_SETTINGS_PATH" "$VSCODE_SETTINGS_SYMLINK_PATH"
    fi
    if ! [ -f "$VSCODE_KEYBINDINGS_SYMLINK_PATH" ]; then
        ln -s "$VSCODE_KEYBINDINGS_PATH" "$VSCODE_KEYBINDINGS_SYMLINK_PATH"
    fi
}
